### PR TITLE
Handle add/remove of master hosts

### LINKED ISSUE #240: Adding new masters to existing cluster does not work
At least we should block control-plane scaling until we have proper logic in place.

### PR DESCRIPTION
**Pull request by jakolehm**
Adds logic for adding/removing masters. It allows to grow number of masters one-by-one (reason for this is internal etcd clustering). Multiple masters can be removed  at the same time from cluster if majority is kept in place. These rules do not apply if cluster.yml is configured to use external etcd endpoints.

Fixes #240

### CODE REVIEW

File: lib/pharos/phases/configure_etcd_changes.rb [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+module Pharos
+  module Phases
+    class ConfigureEtcdChanges < Pharos::Phase
+      title 'Configure etcd member changes'
+
+      def call
+        store_initial_cluster_state
+
+        if etcd.healthy?
+          add_new_members if initial_cluster_state == 'existing'
```
Comment (jakolehm) [inline lib/pharos/phases/configure_etcd_changes.rb]: Does not yet handle removal.

File: lib/pharos/phases/configure_master.rb [hunk 2]
```diff
@@ -346,6 +346,11 @@ def push_authentication_token_webhook_config
       end
 
       def configure
+        cfg = generate_config
```
Comment (jakolehm) [inline lib/pharos/phases/configure_master.rb]: This probably fixes some other issues as well. Anyway we need/should rewrite control plane config always.

File: lib/pharos/scripts/configure-etcd.sh [hunk 3]
```diff
@@ -82,7 +82,12 @@ fi
 
 echo "Waiting etcd to launch on port 2380..."
 
-while ! nc -z ${PEER_IP} 2380; do
+etcd_healthy() {
```
Comment (jakolehm) [inline lib/pharos/scripts/configure-etcd.sh]: Had to remove netcat because it gave false positives.

File: lib/pharos/etcd/client.rb [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+    class Client
+      CURL = 'sudo curl -s --connect-timeout 2 --cacert /etc/pharos/pki/ca.pem --cert /etc/pharos/pki/etcd/client.pem --key /etc/pharos/pki/etcd/client-key.pem https://localhost:2379'
+
+      def initialize(ssh)
+        @ssh = ssh
+      end
+
+      def healthy?
+        response = @ssh.exec!("#{CURL}/health")
+        response.stdout == '{"health": "true"}'
```
Comment (SpComb) [inline lib/pharos/etcd/client.rb]: Better to `JSON.parse` instead of comparing the output verbatim?

File: lib/pharos/etcd/client.rb [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+      rescue
+        false
+      end
+
+      # @return [Array<Hash>]
+      def members
+        result = @ssh.exec("#{CURL}/v2/members")
+        JSON.parse(result.stdout)['members']
+      rescue JSON::ParserError
+        []
```
Comment (SpComb) [inline lib/pharos/etcd/client.rb]: Bad idea, just let it raise instead? Is there some known case where this happens?

File: lib/pharos/etcd/client.rb [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+      end
+
+      # @param host [Pharos::Configuration::Host]
+      def add_member(host)
+        @ssh.exec!("#{CURL}/v2/members -X POST -H 'Content-Type: application/json' -d '{\"peerURLs\":[\"https://#{host.peer_address}:2380\"]}'")
```
Comment (SpComb) [inline lib/pharos/etcd/client.rb]: The quoting is going to get funky.... I'd recommend `curl -d @-` and then `stdin: JSON.dumps(...)`

File: lib/pharos/phases/configure_master.rb (hunk 2 above)
Comment (SpComb) [reply lib/pharos/phases/configure_master.rb]: This is going to fail for things like enabling the `@config.audit`, unless you also call `push_audit_config` to write those referenced config files as well.

File: lib/pharos/scripts/configure-etcd.sh [hunk 7]
```diff
@@ -82,7 +82,12 @@ fi
...
+  response=$(curl -s --cacert /etc/pharos/pki/ca.pem --cert /etc/pharos/pki/etcd/client.pem --key /etc/pharos/pki/etcd/client-key.pem https://${PEER_IP}:2379/health)
+  [ "${response}" = '{"health": "true"}' ]
```
Comment (SpComb) [inline lib/pharos/scripts/configure-etcd.sh]: Something like `jq -r .health <<<"$response"` would be less whitespace-sensitive, but I don't think `jq` is actually installed by default.

**Comment by jakolehm** [comment]
> The ConfigureMaster => kubeadm alpha phase ... change is probably a good idea, but is it strictly necessary for this PR?

Cluster will be left in a weird state if the control plane configuration is not updated. I'll reconsider if we can get #277 merged sooner than later.

File: lib/pharos/phases/configure_etcd_changes.rb [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+      # @param peer [Pharos::Configuration::Host]
+      # @return [String]
+      def peer_name(peer)
+        peer_index = @config.etcd_hosts.find_index { |h| h == peer }
+        "etcd#{peer_index + 1}"
+      end
+
+      # @return [Boolean]
+      def first_peer?
+        @config.etcd_hosts[0] == @host
```
Comment (SpComb) [inline lib/pharos/phases/configure_etcd_changes.rb]: Not used, yet?

**Comment by SpComb** [comment]
> The ConfigureMaster => kubeadm alpha phase ... change is probably a good idea, but is it strictly necessary for this PR?
> 
> Cluster will be left in a weird state if the control plane configuration is not updated. I'll reconsider if we can get #277 merged sooner than later.

No need, it's fine to do this here if it's needed, I just want to understand why.

Seems like the `--apiserver-count` and `etcd.endpoints` change.

File: lib/pharos/etcd/client.rb [hunk 9]
```diff
@@ -0,0 +1,34 @@
+# frozen_string_literal: true
+require 'json'
+
+module Pharos
+  module Etcd
+    class Client
+      CURL = 'sudo curl -s --connect-timeout 2 --cacert /etc/pharos/pki/ca.pem --cert /etc/pharos/pki/etcd/client.pem --key /etc/pharos/pki/etcd/client-key.pem https://localhost:2379'
```
Comment (SpComb) [inline lib/pharos/etcd/client.rb]: `curl -sSf` would be best, in order to handle HTTP API errors as SSH exec errors.

File: lib/pharos/phases/configure_etcd_changes.rb [hunk 10]
```diff
@@ -0,0 +1,77 @@
...
+      end
+
+      def add_new_members
+        member_list = etcd.members
+        new_members = @config.etcd_hosts.select { |h|
+          !member_list.find { |m|
+            m['name'] == peer_name(h) && m['peerURLs'] == ["https://#{h.peer_address}:2380"]
+          }
+        }
+        if new_members.size > (member_list.size / 2.0).ceil
```
Comment (jakolehm) [inline lib/pharos/phases/configure_etcd_changes.rb]: This is not perfect.. suggestions?

Comment (kke) [reply lib/pharos/phases/configure_etcd_changes.rb]: `new_members.size / member_list.size.to_f >= 0.5` ?

Comment (SpComb) [reply lib/pharos/phases/configure_etcd_changes.rb]: Yeah, the `new_members.size > (member_list.size / 2.0).ceil` would allow you to add three new members to an existing cluster of two members: `['c', 'd', 'e'].size > (['a', 'b', 'c', 'd', 'e'].size / 2.0).ceil => false`

The `new_members.size / member_list.size.to_f >= 0.5` is also wrong, it would refuse to add 1 new member bring the cluster to two members: `['a'].size / ['a', 'b'].size.to_f >= 0.5 => true`

Comment (jakolehm) [reply lib/pharos/phases/configure_etcd_changes.rb]: It's still a bit unclear if we can actually add more than one peer at once.

Comment (SpComb) [reply lib/pharos/phases/configure_etcd_changes.rb]: However, I figure the existing condition is probably correct... if you want to be able to scale the cluster up from one member to two members, then you will have to allow breaking the quorum by one node when adding the new member.

If you wanted the cluster to retain quorum with the new members added, then it would be something like `unless member_list.size - new_members.size >= member_list.size / 2 + 1`, but that would make it impossible to scale up a cluster from one node.

Comment (SpComb) [reply lib/pharos/phases/configure_etcd_changes.rb]: > It's still a bit unclear if we can actually add more than one peer at once.

Yes, the best approach would be to add one new peer at a time, waiting for the new peer to successfully join the cluster before adding the next one.

File: lib/pharos/cluster_manager.rb [hunk 11]
```diff
@@ -40,30 +40,47 @@ def validate
...
+      }
+      if master
+        master
+      else
+        config.master_host
+      end
+    end
+
     def apply_phases
+      master = preferred_master_host
```
Comment (jakolehm) [inline lib/pharos/cluster_manager.rb]: @SpComb wdyt? This allows to replace the "first" master host.

Comment (jakolehm) [reply lib/pharos/cluster_manager.rb]: I mean: first master is not always the best one...

Comment (SpComb) [reply lib/pharos/cluster_manager.rb]: Sure, although if you're using `api.endpoint` then it doesn't really matter which host you select... this is more explicit in #278

:-1: for using SSH to check for the `/etc/kubernetes/kubelet.conf` though... why not just use `https://#{host.address}:6443/healthz` to select a working master instead?

Comment (jakolehm) [reply lib/pharos/cluster_manager.rb]: We could check api health.. but it's not guaranteed to have any healthy master. Still we should prefer a master that has generated config (because of etcd, ca, etc..)

Comment (SpComb) [reply lib/pharos/cluster_manager.rb]: > Still we should prefer a master that has generated config (because of etcd, ca, etc..)

But the `master` is not used for that, that uses whatever host the `ConfigureSecretsEncryption`, `ConfigureEtcdCa` etc phases run on first.

Comment (SpComb) [reply lib/pharos/cluster_manager.rb]: > We could check api health.. but it's not guaranteed to have any healthy master

Having the kube-apiserver `/healthz` return HTTP 200 ok is more likely to indicate a healthy master than checking for the existence of `/etc/kubernetes/kubelet.conf`?

File: lib/pharos/cluster_manager.rb [hunk 12]
```diff
@@ -40,30 +40,47 @@ def validate
...
+        apply_phase(Phases::ConfigureCfssl, config.etcd_hosts, ssh: true, parallel: true)
+        apply_phase(Phases::ConfigureEtcdCa, config.etcd_hosts[0...1], ssh: true, parallel: false)
+        apply_phase(Phases::ConfigureEtcdChanges, config.etcd_hosts[0...1], ssh: true, parallel: false)
+        apply_phase(Phases::ConfigureEtcd, config.etcd_hosts, ssh: true, parallel: true)
+      end
 
       apply_phase(Phases::ConfigureSecretsEncryption, config.master_hosts, ssh: true, parallel: false)
       apply_phase(Phases::ConfigureMaster, config.master_hosts, ssh: true, parallel: false)
-      apply_phase(Phases::MigrateWorker, config.worker_hosts, ssh: true, parallel: true, master: config.master_host)
+      apply_phase(Phases::MigrateWorker, config.worker_hosts, ssh: true, parallel: true, master: master)
```
Comment (SpComb) [inline lib/pharos/cluster_manager.rb]: This is going to bug out if the master changes... I already fixed this as part of #278, I'll split that out as a separate fix PR.

Comment (SpComb) [reply lib/pharos/cluster_manager.rb]: See #302

**Comment by jakolehm** [comment]
@SpComb @jnummelin PTAL

File: lib/pharos/cluster_manager.rb [hunk 13]
```diff
@@ -40,33 +40,76 @@ def validate
...
+    def sorted_master_hosts
+      @sorted_master_hosts ||= config.master_hosts.sort_by { |h| master_sort_score(h) }
+    end
+
+    # @param host [Pharos::Configuration::Host]
+    # @return [Integer]
+    def master_sort_score(host)
+      score = 0
+      return score if host.checks['api_healthy']
+      score += 1
```
Comment (SpComb) [inline lib/pharos/cluster_manager.rb]: This control flow is really weird

```ruby
class Pharos::Configuration::Host
  def master_sort_score
    if checks['api_healthy']
      0
    elsif checks['kubelet_configured']
      1
    else
      2
    end
  end
end
```

File: lib/pharos/cluster_manager.rb [hunk 14]
```diff
@@ -40,33 +40,76 @@ def validate
       addon_manager.validate
     end
 
+    # @return [Array<Pharos::Configuration::Host>]
+    def sorted_master_hosts
+      @sorted_master_hosts ||= config.master_hosts.sort_by { |h| master_sort_score(h) }
```
Comment (SpComb) [inline lib/pharos/cluster_manager.rb]: I'm pretty sure that this should be an instance method on the `Pharos::Config` class?

Comment (SpComb) [reply lib/pharos/cluster_manager.rb]: The `@sorted_master_hosts` memoization is also risky, because the sort scoring changes... although it would crash on the uninitialized `checks` in that case, so I guess that's good.

File: lib/pharos/etcd/client.rb [hunk 15]
```diff
@@ -0,0 +1,47 @@
...
+        return false if result.error?
+
+        data = JSON.parse(result.stdout)
+        data['health'] == 'true'
+      end
+
+      # @return [Array<Hash>]
+      def members
+        result = @ssh.exec("#{CURL}/v2/members")
+        raise Error, "Cannot fetch etcd members" if result.error?
```
Comment (SpComb) [inline lib/pharos/etcd/client.rb]: This loses the `curl` `stderr` output? Why not just use `exec!` like the other methods?

Comment (jakolehm) [reply lib/pharos/etcd/client.rb]: I can change this.. reason for not using `exec!` is more clear error message.

Comment (SpComb) [reply lib/pharos/etcd/client.rb]: Yes, I imagine that having the complete `curl` command in the error message would look ugly... maybe have a `curl` helper method that raises `Error` and includes the requested URL + `result.stderr` from curl?

File: lib/pharos/cluster_manager.rb [hunk 16]
```diff
@@ -40,33 +40,76 @@ def validate
...
 
       # master is now configured and can be used
-      apply_phase(Phases::ConfigureDNS, [config.master_host], master: config.master_host)
-      apply_phase(Phases::ConfigureWeave, [config.master_host], master: config.master_host) if config.network.provider == 'weave'
-      apply_phase(Phases::ConfigureCalico, [config.master_host], master: config.master_host) if config.network.provider == 'calico'
-      apply_phase(Phases::ConfigureMetrics, [config.master_host], master: config.master_host)
-      apply_phase(Phases::StoreClusterYAML, [config.master_host], master: config.master_host, config_content: @config_content)
-      apply_phase(Phases::ConfigureBootstrap, [config.master_host], ssh: true) # using `kubeadm token`, not the kube API
+      apply_phase(Phases::ConfigureDNS, [master_hosts.first], master: master_hosts.first)
+
```
Comment (SpComb) [inline lib/pharos/cluster_manager.rb]: spurious empty line?

File: lib/pharos/scripts/configure-etcd.sh [hunk 17]
```diff
@@ -83,9 +94,7 @@ EOF
 fi
 
 echo "Waiting etcd to launch on port 2380..."
-
-while ! nc -z ${PEER_IP} 2380; do
+while ! etcd_healthy; do
```
Comment (jnummelin) [inline lib/pharos/scripts/configure-etcd.sh]: I think we should put some timeouts (5min or something long enough) around these sleep loops

File: lib/pharos/cluster_manager.rb (hunk 13 above)
Comment (jnummelin) [reply lib/pharos/cluster_manager.rb]: I agree, pretty hard to read as-is.

File: lib/pharos/cluster_manager.rb [hunk 18]
```diff
@@ -40,33 +40,76 @@ def validate
...
     end
 
+    # @return [Array<Pharos::Configuration::Host>]
+    def sorted_master_hosts
+      @sorted_master_hosts ||= config.master_hosts.sort_by { |h| master_sort_score(h) }
+    end
+
+    # @param host [Pharos::Configuration::Host]
+    # @return [Integer]
+    def master_sort_score(host)
```
Comment (jnummelin) [inline lib/pharos/cluster_manager.rb]: Some commentary why we sort the masters would be nice, I'm not sure if I can 100% understand why...

**Comment by jnummelin** [comment]
Is there a docs PR already in place?

File: lib/pharos/phases/validate_host.rb [hunk 19]
```diff
@@ -76,6 +77,30 @@ def cpu_arch
...
+      def master_checks
+        data = {}
+        result = @ssh.exec("sudo curl -sSf --connect-timeout 1 --cacert /etc/kubernetes/pki/ca.crt https://localhost:6443/healthz")
+        data['api_healthy'] = (result.success? && result.stdout == 'ok')
+        data['ca_exists'] = @ssh.file('/etc/kubernetes/pki/ca.key').exist?
+
+        unless @config.etcd&.endpoints
+          etcd = Pharos::Etcd::Client.new(@ssh)
+          data['etcd_healthy'] = etcd.healthy?
+          data['etcd_ca_exists'] = @ssh.file('/etc/pharos/pki/etcd/ca-key.pem').exist?
```
Comment (SpComb) [inline lib/pharos/phases/validate_host.rb]: Wrong path, should be `/etc/pharos/pki/ca-key.pem`


```
    $ sudo sh -c 'test -e /etc/pharos/pki/etcd/ca-key.pem && echo true || echo false'
    false
    ! 0
```

**Comment by SpComb** [comment]
This PR also has a new requirement that (master) hosts machines must have unique hostnames... that should probably be explicitly validated before the etcd cluster setup fails.

**Comment by jakolehm** [comment]
> This PR also has a new requirement that (master) hosts machines must have unique hostnames... that should probably be explicitly validated before the etcd cluster setup fails.

Pharos (Kubernetes) already has this requirement.. it's not specific to this PR. But I agree that we should validate it.

File: lib/pharos/etcd/client.rb (hunk 15 above)
Comment (jakolehm) [reply lib/pharos/etcd/client.rb]: Etcd client is now refactored.

File: lib/pharos/cluster_manager.rb (hunk 14 above)
Comment (jakolehm) [reply lib/pharos/cluster_manager.rb]: I can remove memoization, it's not really needed.

File: lib/pharos/cluster_manager.rb (hunk 13 above)
Comment (jakolehm) [reply lib/pharos/cluster_manager.rb]: Fixed.

**Comment by jnummelin** [comment]
> Not sure what kind of docs this PR needs. This fixes several cases that user expects to work.

Maybe something around the limitations, e.g. the case of role changes. Myself as a user stumbled on that. ;)

File: lib/pharos/cluster_manager.rb (hunk 18 above)
Comment (jakolehm) [reply lib/pharos/cluster_manager.rb]: Added some commentary.

**Comment by jakolehm** [comment]
> Maybe something around the limitations, e.g. the case of role changes. Myself as a user stumbled on that. ;)

It's a different issue that we need to fix (at least have validation).

File: lib/pharos/phases/configure_etcd_changes.rb [hunk 20]
```diff
@@ -0,0 +1,79 @@
...
+
+      def remove_old_members
+        member_list = etcd.members
+        remove_members = member_list.reject { |m|
+          @config.etcd_hosts.find { |h|
+            m['peerURLs'] == ["https://#{h.peer_address}:2380"]
+          }
+        }
+        if remove_members.size / member_list.size.to_f >= 0.5
+          fail "Cannot remove majority of etcd peers"
```
Comment (SpComb) [inline lib/pharos/phases/configure_etcd_changes.rb]: Not sure about why this restriction is needed... does this prevent you from replacing either node if you have two master hosts?

Comment (jakolehm) [reply lib/pharos/phases/configure_etcd_changes.rb]: Yes, it should prevent it. If you remove 50% from etcd cluster then it goes into unhealthy state... not sure if we should allow it.

File: lib/pharos/phases/configure_etcd_changes.rb [hunk 21]
```diff
@@ -0,0 +1,79 @@
...
+
+module Pharos
+  module Phases
+    class ConfigureEtcdChanges < Pharos::Phase
+      title 'Configure etcd member changes'
+
+      def call
+        store_initial_cluster_state
+
+        return if initial_cluster_state != 'existing' || !etcd.healthy?
```
Comment (SpComb) [inline lib/pharos/phases/configure_etcd_changes.rb]: This can't be used to repair an unhealthy etcd cluster by adding a new member or replacing failed members?

Comment (jakolehm) [reply lib/pharos/phases/configure_etcd_changes.rb]: Currently no, I have not tested recovery from unhealthy state.

Comment (SpComb) [reply lib/pharos/phases/configure_etcd_changes.rb]: Right now the "recover from broken etcd cluster" case isn't working... but that might be because we have a `GET /v2/keys/foo` healthcheck on the etcd pod, so the kubelet ends up killing all the etcd members once the cluster goes unhealthy...

Once the `etcd` restarts, it seems like there's some kind of startup delay where it just times out all client requests if the cluster is unhealthy cluster... but I did eventually seem to get a response for `GET /v2/members` before the kubelet killed the etcd pod again, so I think it *might* be possible to recover an unhealthy cluster by replacing the failed member?

Comment (jakolehm) [reply lib/pharos/phases/configure_etcd_changes.rb]: I tried this but it seems that broken cluster peer does not respond at all. I think it's out of scope of this PR to fix this broken etcd cluster.

Comment (SpComb) [reply lib/pharos/phases/configure_etcd_changes.rb]: Still thinking this might behave better without the `etcd.healthy?` check... then it would fail right on the `Configure etcd member changes` => get member list, rather than continuing on to the `Configure etcd` and then just hanging because the new member can't join the cluster.
