### PR TITLE
Validate cluster.yml address format

### LINKED ISSUE #811: ExecutionError : SocketError : getaddrinfo: Name or service not known
When I try to run command : pharos up -c cluster.yml

it gave me this error : 

==> KONTENA PHAROS v2.0.2-rc.1 (Kubernetes v1.11.4)
==> Reading instructions ...
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
==> Gather host facts @ 10.200.224.1 10.200.224.9  10.200.224.8 10.200.247.255 10.200.224.2 10.200.224.3 10.200.224.4
ERROR: Clamp::ExecutionError : SocketError : getaddrinfo: Name or service not known

I tried it on different versions 2.0.1 and 2.0.0 I got the same issue .

I'm sure from the ssh key I'm trying to install kubernetes on baremetal servers.

KR
Amm

### PR DESCRIPTION
**Pull request by kke**
Validates host address and private_address syntax.

Would have fixed #811

### CODE REVIEW

File: lib/pharos/config_schema.rb [hunk 1]
```diff
@@ -36,22 +36,37 @@ def self.load(data)
       result.to_h
     end
 
+    module CustomPredicates
+      include Dry::Logic::Predicates
+
+      predicate(:hostname_or_ip?) do |value|
+        value.match?(/\A\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\z/) || value.match?(/\A[a-z0-9\-\.]+\z/)
```
Comment (jakolehm) [inline lib/pharos/config_schema.rb]: IMHO we need specs for this validation.
