### PR TITLE
Fix external etcd

### LINKED ISSUE #274: Configuring external etcd still configures etcd on each master node
If configured with external etcd, the `ConfigureEtcdCa` and `ConfigureEtcd` phases should not configure etcd to run on each master node.

This will cause the `pharos-cluster up` to get stuck on `Waiting etcd to launch on port 2380...` if etcd is already running on the master nodes:

```
$ docker logs k8s_etcd_etcd-terom-kupo-master_kube-system_842d9012e8f6229ffcbeb20182a8e79d_5
2018-04-19 10:53:01.800768 I | etcdmain: etcd Version: 3.1.12
2018-04-19 10:53:01.800837 I | etcdmain: Git SHA: 918698add
2018-04-19 10:53:01.800844 I | etcdmain: Go Version: go1.8.7
2018-04-19 10:53:01.800848 I | etcdmain: Go OS/Arch: linux/amd64
2018-04-19 10:53:01.800854 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2018-04-19 10:53:01.800905 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-04-19 10:53:01.800921 I | embed: peerTLS: cert = /etc/kubernetes/pki/etcd/peer.pem, key = /etc/kubernetes/pki/etcd/peer-key.pem, ca = , trusted-ca = /etc/kubernetes/pki/ca.pem, client-cert-auth = true
2018-04-19 10:53:01.827814 I | embed: listening for peers on https://167.99.36.141:2380
2018-04-19 10:53:01.827895 I | embed: listening for client requests on 167.99.36.141:2379
2018-04-19 10:53:01.828763 I | embed: stopping listening for client requests on localhost:2379
2018-04-19 10:53:01.828800 C | etcdmain: listen tcp 127.0.0.1:2379: bind: address already in use
```

### LINKED ISSUE #275: Configuring external etcd certificates is broken
Still calling the `@ssh.write_file(...)` method that no longer exists.

```
    [167.99.36.141] Pushing external etcd certificates ...
    $ sudo mkdir -p /etc/pharos/etcd
    ! 0
undefined method `write_file' for #<Pharos::SSH::Client:0x0000000002a05ee0>
/app/lib/pharos/phases/configure_master.rb:184:in `copy_external_etcd_certs'
/app/lib/pharos/phases/configure_master.rb:53:in `install'
/app/lib/pharos/phases/configure_master.rb:22:in `call'
/app/lib/pharos/phase_manager.rb:70:in `block in apply'
/app/lib/pharos/phase_manager.rb:40:in `block in run_serial'
/app/lib/pharos/phase_manager.rb:39:in `map'
/app/lib/pharos/phase_manager.rb:39:in `run_serial'
/app/lib/pharos/phase_manager.rb:51:in `run'
/app/lib/pharos/phase_manager.rb:67:in `apply'
/app/lib/pharos/cluster_manager.rb:74:in `apply_phase'
/app/lib/pharos/cluster_manager.rb:52:in `apply_phases'
/app/lib/pharos/up_command.rb:106:in `configure'
/app/lib/pharos/up_command.rb:45:in `block in execute'
/app/lib/pharos/up_command.rb:43:in `chdir'
/app/lib/pharos/up_command.rb:43:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:14:in `run'
bin/pharos-cluster:12:in `<main>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #274
Fixes #275

### CODE REVIEW

File: lib/pharos/cluster_manager.rb [hunk 1]
```diff
@@ -45,7 +45,7 @@ def apply_phases
       apply_phase(Phases::MigrateMaster, config.master_hosts, ssh: true, parallel: true)
       apply_phase(Phases::ConfigureHost, config.hosts, ssh: true, parallel: true)
       apply_phase(Phases::ConfigureCfssl, config.etcd_hosts, ssh: true, parallel: true)
-      apply_phase(Phases::ConfigureEtcdCa, [config.etcd_host], ssh: true, parallel: false)
+      apply_phase(Phases::ConfigureEtcdCa, config.etcd_hosts[0...1], ssh: true, parallel: false)
```
Comment (SpComb) [inline lib/pharos/cluster_manager.rb]: This is an empty slice if `config.etcd_hosts` is empty.
