### PR TITLE
Remove unix:// prefix from container-runtime-endpoint

### LINKED ISSUE #969: Metrics missing on Bionic & CRI-O
**What happened**:

Metrics for pods not available on Bionic & CRI-O

**What you expected to happen**:

Metrics to be available

**How to reproduce it (as minimally and precisely as possible)**:

Deploy cluster on Bionic & CRI-O.

Metrics server logs the following:
```
E0111 14:00:03.879110       1 manager.go:102] unable to fully collect metrics: 
    [unable to fully scrape metrics from source kubelet_summary:jussi-pharos-master-0: 
        [unable to get CPU for container "kube-controller-manager" in pod kube-system/kube-controller-manager-jussi-pharos-master-0 on node "10.133.86.156", discarding data: missing cpu usage metric,
        unable to get CPU for container "etcd" in pod kube-system/etcd-jussi-pharos-master-0 on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "coredns" in pod kube-system/coredns-5784d68866-b9cz6 on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "user-authenticator" in pod kontena-lens/user-authenticator-v55nv on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "weave-npc" in pod kube-system/weave-net-99nvd on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "weave" in pod kube-system/weave-net-99nvd on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "kube-proxy" in pod kube-system/kube-proxy-m94pp on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "kube-scheduler" in pod kube-system/kube-scheduler-jussi-pharos-master-0 on node "10.133.86.156", discarding data: missing cpu usage metric, 
        unable to get CPU for container "kube-apiserver" in pod kube-system/kube-apiserver-jussi-pharos-master-0 on node "10.133.86.156", discarding data: missing cpu usage metric
        ], 
```

That repeats for every node and for every container on each node.

**Anything else we need to know?**:

**Environment**:
- Pharos version (use `pharos --version`): 2.1.5
- Cloud provider or hardware configuration: DO, Bionic, CRI-O
- OS (e.g. from /etc/os-release; both for the client and for the used nodes): Ubuntu Bionic
- Others:

**cluster.yml:**

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #969

### CODE REVIEW

File: lib/pharos/configuration/host.rb [hunk 1]
```diff
@@ -145,7 +145,7 @@ def kubelet_args(local_only: false, cloud_provider: nil)
         if crio?
           args << '--container-runtime=remote'
           args << '--runtime-request-timeout=15m'
-          args << '--container-runtime-endpoint=unix:///var/run/crio/crio.sock'
+          args << '--container-runtime-endpoint=/var/run/crio/crio.sock'
```
Comment (jnummelin) [inline lib/pharos/configuration/host.rb]: Maybe add some comment & link to upstream issue why the path need to be without the prefix

Comment (jakolehm) [reply lib/pharos/configuration/host.rb]: Done.
