### PR TITLE
Fix global option parsing and phase thread error handling

### LINKED ISSUE #1135: 2.3.0-alpha.1 Error without backtrace
I am getting a new error that I was not getting with v2.2.3.

Full debug output:

```
==> KONTENA PHAROS v2.3.0-alpha.1+oss (Kubernetes v1.13.3)
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
    [localhost] Upgrade check encountered an error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:

            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
or:
            `Excon.defaults[:ssl_verify_peer] = false` (less secure).
 : SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized:

            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
or:
            `Excon.defaults[:ssl_verify_peer] = false` (less secure).

    [localhost] Completed phase in 0.26s
ERROR: IPAddr::InvalidAddressError : invalid address
```
The cert issue is odd, but also happens on my successful 2.2.3 run. The IPAddr error has no backtrace, and comes somewhere between phases. Very odd and hard to debug.

### PR DESCRIPTION
**Pull request by kke**
Fixes #1135
Closes #1136 (alternative)

Also changes the phase exception handling to let other hosts finish before reporting exceptions to avoid leaving hosts in unexpected states.

### CODE REVIEW

File: bin/pharos [hunk 1]
```diff
@@ -8,5 +8,12 @@ $LOAD_PATH.unshift lib_path unless $LOAD_PATH.include?(lib_path)
 
 STDOUT.sync = true
 
+# rubocop:disable Lint/HandleExceptions
+begin
+  require 'bundler/setup'
```
Comment (kke) [inline bin/pharos]: With this, you can do `bin/pharos` instead of `bundle exec bin/pharos` which has started to output super verbose error messages with issue templates and what not.

File: lib/pharos/command.rb [hunk 2]
```diff
@@ -12,8 +12,14 @@ def self.options(*option_names)
       end
     end
 
-    def run(*_args)
+    def parse(*_arguments)
```
Comment (kke) [inline lib/pharos/command.rb]: Instead of reimplementing `run` like in #1136 - override parse. Now we can just super in both.

File: lib/pharos/transport/command/result.rb [hunk 3]
```diff
@@ -115,22 +115,16 @@ def debug_exit(exit_status)
...
 
-        if !ENV['DEBUG'].to_s.empty?
-          def debug(&block)
-            instance_exec(&block)
-          end
-        else
-          def debug(&_block)
-            nil
-          end
+        def debug(&block)
```
Comment (kke) [inline lib/pharos/transport/command/result.rb]: The previous implementation required the ENV to be set already when the class was being loaded, which made `--debug` not enable the SSH debug correctly.

File: lib/pharos/phase_manager.rb [hunk 4]
```diff
@@ -30,12 +30,23 @@ def initialize(**options)
...
-      threads = phases.map { |phase|
+      threads = phases.map do |phase|
         Thread.new do
           Thread.current.report_on_exception = false
           Retry.perform(yield_object: phase, logger: logger, exceptions: RETRY_ERRORS, &block)
         end
-      }
+      end
+
+      until threads.none?(&:alive?)
```
Comment (kke) [inline lib/pharos/phase_manager.rb]: This is where the sauce is.

> `abort_on_exception` → true or false
> When set to true, if any thread is aborted by an exception, the raised exception will be re-raised in the main thread.

> `report_on_exception → true or false`
> All threads created when this flag is true will report a message on $stderr if an exception kills the thread.
> This is done to catch errors in threads early. In some cases, you might not want this output. There are multiple ways to avoid the extra output:
> * If the exception is not intended, the best is to fix the cause of the exception so it does not happen anymore.
> * If the exception is intended, it might be better to rescue it closer to where it is raised rather then let it kill the Thread.
> * **If it is guaranteed the Thread will be joined with #join or #value, then it is safe to disable this report** with Thread.current.report_on_exception = false when starting the Thread. However, this might handle the exception much later, or not at all if the Thread is never joined due to the parent thread being blocked, etc

The problem with `abort_on_exception=true` is that the main thread may be anywhere when that happens, which messes up the exception handling and it will miss `Pharos::Command`'s `rescue`s. Relying on `thread.value` to raise, it's possible to rescue reliably exactly where expected.

If the other threads are not killed, they may keep running and outputting until the main thread exits.

File: lib/pharos/phase_manager.rb [hunk 5]
```diff
@@ -30,12 +30,23 @@ def initialize(**options)
...
+        # Thread status is false when terminated normally, nil when it terminated with exception
+        thread_with_exception = threads.find { |thr| thr.status.nil? }
+        if thread_with_exception
+          threads.map(&:kill) # kill other threads
+          thread_with_exception.value # raises the exception
+        end
+        Thread.pass
```
Comment (kke) [inline lib/pharos/phase_manager.rb]: Without this the loop hogs all the cpu and the threads become super slow.

File: lib/pharos/phase_manager.rb [hunk 6]
```diff
@@ -30,12 +30,23 @@ def initialize(**options)
...
         end
-      }
+      end
+
+      until threads.none?(&:alive?)
+        # Thread status is false when terminated normally, nil when it terminated with exception
+        thread_with_exception = threads.find { |thr| thr.status.nil? }
+        if thread_with_exception
+          threads.map(&:kill) # kill other threads
+          thread_with_exception.value # raises the exception
```
Comment (kke) [inline lib/pharos/phase_manager.rb]: > `value → obj`
> Waits for thr to complete, using join, and returns its value or **raises the exception which terminated the thread**.

File: bin/pharos (hunk 1 above)
Comment (jakolehm) [reply bin/pharos]: What do you mean by issue templates? I think this does add some overhead?

File: lib/pharos/phase_manager.rb [hunk 7]
```diff
@@ -30,12 +30,23 @@ def initialize(**options)
...
           Retry.perform(yield_object: phase, logger: logger, exceptions: RETRY_ERRORS, &block)
         end
-      }
+      end
+
+      until threads.none?(&:alive?)
+        # Thread status is false when terminated normally, nil when it terminated with exception
+        thread_with_exception = threads.find { |thr| thr.status.nil? }
+        if thread_with_exception
+          threads.map(&:kill) # kill other threads
```
Comment (jakolehm) [inline lib/pharos/phase_manager.rb]: I don't think this is safe assumption.

Comment (jakolehm) [reply lib/pharos/phase_manager.rb]: Actually it works like it has been working.. now that it's written out it sounds bad.. should we wait all threads to finish before halting whole process?

File: bin/pharos (hunk 1 above)
Comment (kke) [reply bin/pharos]: I don't know how to get it again.

Now I just get the : 
```
$  bundle exec bin/pharos version
bundler: failed to load command: bin/pharos (bin/pharos)
NameError: uninitialized constant Pharos::Clmap
```

Earlier I got a 3-page bundler error report that displayed the Gemfile, error backtrace, instructions how to issue a bug report, a list of questions to answer in the bug report, and a bunch of debug information.

It should only add "overhead" when you have bundler. And when you run `bundle exec` it does the same stuff I believe.

Looks like `bundler/setup` does something with `ENV['DEBUG']` too.

Comment (kke) [reply bin/pharos]: Ha, I got it now again:

```
==> Sharpening tools ...
==> Check for Pharos upgrade @ localhost
    [localhost] Checking for a new version ...
    [localhost] Already at the latest version
    [localhost] Completed phase in 0.09s
==> Open SSH connection @ 192.168.100.100 192.168.100.101 192.168.100.102
    [192.168.100.100] Completed phase in 0.21s
    [192.168.100.101] Completed phase in 0.26s
    [192.168.100.102] Completed phase in 0.07s
==> Gather host facts @ 192.168.100.100 192.168.100.101 192.168.100.102
    [192.168.100.100] Checking sudo access ...
    [192.168.100.101] Checking sudo access ...
    [192.168.100.102] Checking sudo access ...
    got error (RuntimeError): foofoo
    /Users/kimmo/Projects/pc2/lib/pharos/phases/gather_facts.rb:17:in `call'
/Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:73:in `block in apply'
/Users/kimmo/Projects/pc2/lib/pharos/retry.rb:20:in `perform'
/Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:36:in `block (2 levels) in run_parallel'
    got error (RuntimeError): foofoo
rescue 4 of Pharos::Command RuntimeError in Pharos::UpCommand
    /Users/kimmo/Projects/pc2/lib/pharos/phases/gather_facts.rb:17:in `call'
/Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:73:in `block in apply'
/Users/kimmo/Projects/pc2/lib/pharos/retry.rb:20:in `perform'
/Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:36:in `block (2 levels) in run_parallel'
rescue 4 of Pharos::Command RuntimeError in Pharos::RootCommand
    got error (RuntimeError): foofoo
    /Users/kimmo/Projects/pc2/lib/pharos/phases/gather_facts.rb:17:in `call'
/Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:73:in `block in apply'
/Users/kimmo/Projects/pc2/lib/pharos/retry.rb:20:in `perform'
/Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:36:in `block (2 levels) in run_parallel'
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

  I ran the command `bin/pharos up -c buster.yml --debug`

- **What did you expect to happen?**

  I expected Bundler to...

- **What happened instead?**

  Instead, what happened was...

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

  I tried...

- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**

  ...

## Backtrace

---
RuntimeError: foofoo
  /Users/kimmo/Projects/pc2/lib/pharos/phases/gather_facts.rb:17:in `call'
  /Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:73:in `block in apply'
  /Users/kimmo/Projects/pc2/lib/pharos/retry.rb:20:in `perform'
  /Users/kimmo/Projects/pc2/lib/pharos/phase_manager.rb:36:in `block (2 levels) in run_parallel'
---

## Environment

---
Bundler       1.17.2
  Platforms   ruby, x86_64-darwin-18
Ruby          2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
  Full Path   /Users/kimmo/.rbenv/versions/2.6.1/bin/ruby
  Config Dir  /Users/kimmo/.rbenv/versions/2.6.1/etc
RubyGems      3.0.1
  Gem Home    /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0
  Gem Path    /Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0:/Users/kimmo/.gem/ruby/2.6.0
  User Path   /Users/kimmo/.gem/ruby/2.6.0
  Bin Dir     /Users/kimmo/.rbenv/versions/2.6.1/bin
OpenSSL
  Compiled    OpenSSL 1.0.2q  20 Nov 2018
  Loaded      OpenSSL 1.0.2q  20 Nov 2018
  Cert File   /usr/local/etc/openssl/cert.pem
  Cert Dir    /usr/local/etc/openssl/certs
Tools
  Git         2.19.0
  RVM         not installed
  rbenv       rbenv 1.1.1
  chruby      not installed
---

## Bundler Build Metadata

---
Built At          2018-12-19
Git SHA           3fc4de72b
Released Version  false
---

## Bundler settings

---
gem.test
  Set for the current user (/Users/kimmo/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/kimmo/.bundle/config): false
gem.coc
  Set for the current user (/Users/kimmo/.bundle/config): false
bin_path
  Set via BUNDLE_BIN_PATH: "/Users/kimmo/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle"
gemfile
  Set via BUNDLE_GEMFILE: "/Users/kimmo/Projects/pc2/Gemfile"
---

## Gemfile

### Gemfile

---ruby
source "https://rubygems.org"

gemspec
---

### Gemfile.lock

---
PATH
  remote: .
  specs:
    pharos-cluster (2.3.0.alpha.1)
      bcrypt (~> 3.1)
      bcrypt_pbkdf (~> 1.0)
      clamp (= 1.2.1)
      dry-logic (= 0.4.2)
      dry-struct (= 0.5.0)
      dry-types (= 0.13.2)
      dry-validation (= 0.12.1)
      ed25519 (~> 1.2)
      excon (~> 0.62.0)
      fugit (~> 1.1.2)
      k8s-client (~> 0.8.1)
      net-ssh (= 5.1.0)
      net-ssh-gateway (= 2.0.0)
      pastel (~> 0.7)
      rouge (~> 3.1)
      tty-prompt (~> 0.16)
      yaml-safe_load_stream (~> 0.1)

GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.0)
    bcrypt (3.1.12)
    bcrypt_pbkdf (1.0.0)
    byebug (11.0.0)
    clamp (1.2.1)
    coderay (1.1.2)
    concurrent-ruby (1.1.4)
    diff-lcs (1.3)
    dry-configurable (0.8.1)
      concurrent-ruby (~> 1.0)
      dry-core (~> 0.4, >= 0.4.7)
    dry-container (0.7.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.4.7)
      concurrent-ruby (~> 1.0)
    dry-equalizer (0.2.1)
    dry-inflector (0.1.2)
    dry-logic (0.4.2)
      dry-container (~> 0.2, >= 0.2.6)
      dry-core (~> 0.2)
      dry-equalizer (~> 0.2)
    dry-struct (0.5.0)
      dry-core (~> 0.4, >= 0.4.3)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.13)
      ice_nine (~> 0.11)
    dry-types (0.13.2)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.3)
      dry-core (~> 0.4, >= 0.4.4)
      dry-equalizer (~> 0.2)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 0.4, >= 0.4.2)
    dry-validation (0.12.1)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-core (~> 0.2, >= 0.2.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      dry-types (~> 0.13.1)
    ed25519 (1.2.4)
    equatable (0.5.0)
    et-orbi (1.1.7)
      tzinfo
    excon (0.62.0)
    fakefs (0.19.2)
    fugit (1.1.8)
      et-orbi (~> 1.1, >= 1.1.7)
      raabro (~> 1.1)
    hashdiff (0.3.8)
    ice_nine (0.11.2)
    jaro_winkler (1.5.2)
    jsonpath (0.9.9)
      multi_json
      to_regexp (~> 0.2.1)
    k8s-client (0.8.3)
      dry-struct (~> 0.5.0)
      excon (~> 0.62.0)
      hashdiff (~> 0.3.7)
      jsonpath (~> 0.9.5)
      recursive-open-struct (~> 1.1.0)
      yajl-ruby (~> 1.4.0)
      yaml-safe_load_stream (~> 0.1)
    method_source (0.9.2)
    multi_json (1.13.1)
    necromancer (0.4.0)
    net-ssh (5.1.0)
    net-ssh-gateway (2.0.0)
      net-ssh (>= 4.0.0)
    parallel (1.13.0)
    parser (2.6.0.0)
      ast (~> 2.4.0)
    pastel (0.7.2)
      equatable (~> 0.5.0)
      tty-color (~> 0.4.0)
    powerpack (0.1.2)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.7.0)
      byebug (~> 11.0)
      pry (~> 0.10)
    psych (3.1.0)
    raabro (1.1.6)
    rainbow (3.0.0)
    rake (10.5.0)
    recursive-open-struct (1.1.0)
    rouge (3.3.0)
    rspec (3.8.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
    rspec-core (3.8.0)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.0)
    rubocop (0.65.0)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      powerpack (~> 0.1)
      psych (>= 3.1.0)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.4.0)
    ruby-progressbar (1.10.0)
    timers (4.3.0)
    to_regexp (0.2.1)
    tty-color (0.4.3)
    tty-cursor (0.6.0)
    tty-prompt (0.18.1)
      necromancer (~> 0.4.0)
      pastel (~> 0.7.0)
      timers (~> 4.0)
      tty-cursor (~> 0.6.0)
      tty-reader (~> 0.5.0)
    tty-reader (0.5.0)
      tty-cursor (~> 0.6.0)
      tty-screen (~> 0.6.4)
      wisper (~> 2.0.0)
    tty-screen (0.6.5)
    tzinfo (2.0.0)
      concurrent-ruby (~> 1.0)
    unicode-display_width (1.4.1)
    wisper (2.0.0)
    yajl-ruby (1.4.1)
    yaml-safe_load_stream (0.1.1)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (>= 1.17.2, <= 3.0)
  fakefs (~> 0.13)
  pharos-cluster!
  pry-byebug (~> 3.6)
  rake (~> 10.0)
  rspec (~> 3.7)
  rubocop (~> 0.57)

BUNDLED WITH
   1.17.2
---

## Gemspecs

### pharos-cluster.gemspec

---ruby
lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "pharos/version"

files = Dir['README.md', 'LICENSE', 'licenses/*', 'bin/*', 'lib/**/*', 'addons/**/*']
require_paths = ['lib']
if ENV['PHAROS_NON_OSS'] == 'true'
  files += Dir['non-oss/**/*']
  require_paths << 'non-oss'
end

Gem::Specification.new do |spec|
  spec.name          = "pharos-cluster"
  spec.version       = Pharos::VERSION.sub('-', '.')
  spec.authors       = ["Kontena, Inc."]
  spec.email         = ["info@kontena.io"]

  spec.summary       = "Kontena Pharos cluster manager"
  spec.homepage      = "https://github.com/kontena/pharos-cluster"
  spec.license       = ENV['PHAROS_NON_OSS'] == 'true' ? "Nonstandard" : "Apache-2.0"

  spec.files         = files
  spec.bindir        = "bin"
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.require_paths = require_paths
  spec.required_ruby_version = '~> 2.5'

  spec.add_runtime_dependency "clamp", "1.2.1"
  spec.add_runtime_dependency "pastel", "~> 0.7"
  spec.add_runtime_dependency "net-ssh", "5.1.0"
  spec.add_runtime_dependency "net-ssh-gateway", "2.0.0"
  spec.add_runtime_dependency "ed25519", "~> 1.2"
  spec.add_runtime_dependency "bcrypt", "~> 3.1"
  spec.add_runtime_dependency "bcrypt_pbkdf", "~> 1.0"
  spec.add_runtime_dependency "dry-types", "0.13.2"
  spec.add_runtime_dependency "dry-validation", "0.12.1"
  spec.add_runtime_dependency "dry-struct", "0.5.0"
  spec.add_runtime_dependency "dry-logic", "0.4.2"
  spec.add_runtime_dependency "fugit", "~> 1.1.2"
  spec.add_runtime_dependency "rouge", "~> 3.1"
  spec.add_runtime_dependency "tty-prompt", "~> 0.16"
  spec.add_runtime_dependency "k8s-client", "~> 0.8.1"
  spec.add_runtime_dependency "yaml-safe_load_stream", "~> 0.1"
  spec.add_runtime_dependency "excon", "~> 0.62.0"

  spec.add_development_dependency "bundler", ">= 1.17.2", "<= 3.0"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rspec", "~> 3.7"
  spec.add_development_dependency "fakefs", "~> 0.13"
  spec.add_development_dependency "rubocop", "~> 0.57"
  spec.add_development_dependency "pry-byebug", "~> 3.6"
end
---

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=foofoo&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

File: lib/pharos/phase_manager.rb (hunk 7 above)
Comment (kke) [reply lib/pharos/phase_manager.rb]: > I don't think this is safe assumption.

Hmm, what is not safe assumption?  `Thread status is false when terminated normally, nil when it terminated with exception` this is fact from the [docs](https://devdocs.io/ruby~2.5/thread#method-i-status) 

> Actually it works like it has been working.. now that it's written out it sounds bad.. should we wait all threads to finish before halting whole process?

Maybe it would be better.

It will delay aborting but shouldn't leave the hosts in a funny state. Maybe larger phases should be split into smaller phases that would complete (and fail) faster.

There was some reason originally to add `Thread.current.abort_on_exception = true` to the pro configure_master

Comment (jakolehm) [reply lib/pharos/phase_manager.rb]: > Hmm, what is not safe assumption? 

Sorry for not being too clear.. I meant that killing other threads sounds a bit unsafe.

Comment (jakolehm) [reply lib/pharos/phase_manager.rb]: Probably the best way to implement this is to gather all exceptions, report them (with or without backtrace) and then raise a "Phase foobar failed" exception. This way we don't need to brutally kill any threads and user can see errors from every parallel phase.

Comment (kke) [reply lib/pharos/phase_manager.rb]: Yeah and that's what happens with `abort_on_exception=true`, and that also happens when you do `threads.map(&:value)`:

```ruby
threads = []
threads << Thread.new { sleep 2; raise "what" }
threads << Thread.new { sleep 5; puts "hello 1" } # <-- will never execute
threads.map(&:value) # because the first `thread.value` call will block + 
                     # reraise, which kills the main thread, which kills
                     # the other threads
```

So we can not call `threads.map(&:join) or `threads.map(&:value)` because both will raise when an exception appears in the thread being waited on.

I think the "let it finish` version would be:

```
Thread.pass until threads.none?(&:alive?)
threads.map(&:value) # this will raise if any of the threads had an exception.
```

**Comment by kke** [comment]
The phases will now finish on other hosts before exceptions are raised.

image

File: bin/pharos (hunk 1 above)
Comment (jakolehm) [reply bin/pharos]: I would leave this out from the PR and create new one which focuses on bundler problem. /cc @jnummelin

Comment (jnummelin) [reply bin/pharos]: yeah, somewhat irrelevant to this PR

**Comment by jakolehm** [comment]
Conflicts...
