### PR TITLE
Load libraries in phase manager to fix version command

### LINKED ISSUE #521: pharos-cluster version throws "uninitialized constant"
```
pharos-cluster version
Kontena Pharos:
  - pharos-cluster version 1.3.0-beta.2
uninitialized constant Pharos::PhaseManager::OpenSSL
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #521

Adds `require`s to phase manager so that it can define the list of retriable errors.

### CODE REVIEW

File: lib/pharos/phase_manager.rb [hunk 1]
```diff
@@ -1,5 +1,10 @@
 # frozen_string_literal: true
 
+require 'openssl'
+require 'excon'
+require 'k8s/error'
+require 'pharos/ssh/remote_command'
```
Comment (jakolehm) [inline lib/pharos/phase_manager.rb]: or just `require_relative 'kube'`?

Comment (jakolehm) [reply lib/pharos/phase_manager.rb]: reason: openssl & excon are `k8s-client` deps
