### PR TITLE
Fix local transport mode detect

### LINKED ISSUE #1278: localmode detection considred harmful
I have a vm running in 127.0.0.1:2222

pharos switches to local mode and starts to use my host machine.

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #1278

### CODE REVIEW

File: lib/pharos/configuration/host.rb [hunk 1]
```diff
@@ -38,6 +38,8 @@ def short_hostname
       end
 
       def local?
+        return false if ssh_key_path || ssh_port || user
```
Comment (kke) [inline lib/pharos/configuration/host.rb]: `ssh_port` has default value of 22

Comment (jakolehm) [reply lib/pharos/configuration/host.rb]: Good catch, fixed.
