### PR TITLE
Fix /etc/resolv.conf parser comment handling

### LINKED ISSUE #614: IPAddr::InvalidAddressError : invalid address Error on setting up the cluster
Hi,

I am trying to setup pharos cluster on ubuntu 18.04 a, getting the following error 

```
    # nameserver config
    nameserver 213.133.100.100
    nameserver 213.133.98.98
    nameserver 213.133.99.99
    nameserver 2a01:4f8:0:1::add:1010
    nameserver 2a01:4f8:0:1::add:9898
    nameserver 2a01:4f8:0:1::add:9999
    ! 0
invalid address
/__enclose_io_memfs__/lib/ruby/2.4.0/ipaddr.rb:563:in `in6_addr'
/__enclose_io_memfs__/lib/ruby/2.4.0/ipaddr.rb:500:in `initialize'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `new'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `block in check_resolvconf_nameserver_localhost'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `map'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:118:in `check_resolvconf_nameserver_localhost'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:132:in `read_resolvconf'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:29:in `gather_host_facts'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phases/gather_facts.rb:14:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phase_manager.rb:92:in `block in apply'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phase_manager.rb:53:in `yield_phase_with_retry'
/__enclose_io_memfs__/lib/ruby/gems/2.4.0/gems/pharos-cluster-1.3.2/lib/pharos/phase_manager.rb:34:in `block (2 levels) in run_parallel'
```
Does it have something to do with IPv6/6 ?

### PR DESCRIPTION
**Pull request by kke**
Fixes #614

Also checks for ipv6 loopback nameservers.

### CODE REVIEW

File: lib/pharos/phases/gather_facts.rb [hunk 1]
```diff
@@ -98,39 +98,28 @@ def private_interface_address(interface)
...
-
-        @ssh.file('/etc/resolv.conf').each_line do |line|
-          if match = line.match(/nameserver (.+)/)
-            nameservers << match[1]
-          end
-        end
-
-        nameservers
+      def resolvconf_nameservers
+        @ssh.file('/etc/resolv.conf').lines.map { |l| l[/^nameserver ([\h:.]+)/, 1] }.compact
```
Comment (kke) [inline lib/pharos/phases/gather_facts.rb]: `\h` = hex charset

File: lib/pharos/phases/gather_facts.rb [hunk 2]
```diff
@@ -98,39 +98,28 @@ def private_interface_address(interface)
...
 
-      LOCALNET = IPAddr.new('127.0.0.0/8')
-
       # Host /etc/resolv.conf is configured to use a nameserver at localhost in the host network namespace
       # @return [Boolean]
-      def check_resolvconf_nameserver_localhost
-        resolvers = read_resolvconf_nameservers.map{ |ip| IPAddr.new(ip) }
-        resolvers.any? { |ip| LOCALNET.include?(ip) }
+      def resolvconf_nameserver_localhost?
+        resolvconf_nameservers.any? { |ip| IPAddr.new(ip).loopback? }
```
Comment (kke) [inline lib/pharos/phases/gather_facts.rb]: [`IPAddr#loopback?`](https://ruby-doc.org/stdlib-2.5.1/libdoc/ipaddr/rdoc/IPAddr.html#method-i-loopback-3F) checks for `127.0.0.0/8` + `::1`

File: lib/pharos/phases/gather_facts.rb [hunk 3]
```diff
@@ -98,39 +98,28 @@ def private_interface_address(interface)
...
       end
 
       # Host /etc/resolv.conf is configured to use the systemd-resolved stub resolver at 127.0.0.53
       # @return [Boolean]
-      def check_resolvconf_systemd_resolved_stub
+      def resolvconf_systemd_resolved_stub?
```
Comment (kke) [inline lib/pharos/phases/gather_facts.rb]: Changed to imply booleanness

File: lib/pharos/ssh/remote_file.rb [hunk 4]
```diff
@@ -91,12 +91,16 @@ def readlink
         target
       end
 
+      # Returns an array of lines in the remote file
+      # @return [Array<String>]
+      def lines
+        read.lines
```
Comment (kke) [inline lib/pharos/ssh/remote_file.rb]: String has `.lines` and `.each_line`, not worth replicating here.

File: lib/pharos/ssh/remote_file.rb [hunk 5]
```diff
@@ -91,12 +91,16 @@ def readlink
...
+      end
+
       # Yields each line in the remote file
       # @yield [String]
-      def each_line
-        read.split(/[\r\n]/).each do |row|
```
Comment (kke) [inline lib/pharos/ssh/remote_file.rb]: (This would cause windows/mac `\r\n` / `\n\r` linefeeds to yield extra blank lines, not an issue here, just noting).

File: lib/pharos/phases/gather_facts.rb (hunk 2 above)
Comment (kke) [reply lib/pharos/phases/gather_facts.rb]: aaaand it came in ruby 2.5

File: lib/pharos/phases/gather_facts.rb [hunk 6]
```diff
@@ -98,39 +98,46 @@ def private_interface_address(interface)
...
-      def read_resolvconf_nameservers
-        nameservers = []
+      def resolvconf_nameservers
+        @ssh.file('/etc/resolv.conf').lines.map { |l| l[/^nameserver ([\h:.]+)/, 1] }.compact
+      end
 
-        @ssh.file('/etc/resolv.conf').each_line do |line|
-          if match = line.match(/nameserver (.+)/)
-            nameservers << match[1]
+      module IPAddrLoopbackBackport
```
Comment (jakolehm) [inline lib/pharos/phases/gather_facts.rb]: Maybe this should be in a separate file?
