### PR TITLE
Fix listing of addons

### LINKED ISSUE #244: pharos-cluster version does not list addons
```
$ ./bin/pharos-cluster version
pharos-cluster version 0.5.0
3rd party versions:
  - cfssl=1.2 (MIT)
  - etcd=3.1.12 (Apache License 2.0)
  - docker=1.13.1 (Apache License 2.0)
  - cri-o=1.9 (Apache License 2.0)
  - kubernetes=1.9.6 (Apache License 2.0)
  - heapster=1.5.1 (Apache License 2.0)
  - weave-net=2.3.0 (Apache License 2.0)
Addon versions:
```

### PR DESCRIPTION
**Pull request by jakolehm**
Fixes #244

### CODE REVIEW

File: lib/pharos/version_command.rb [hunk 1]
```diff
@@ -5,18 +5,31 @@ class VersionCommand < Pharos::Command
...
+    def phases
+      Pharos::Phases.components.sort_by(&:name)
+    end
+
+    def addons
+      Pharos::AddonManager.new(Pharos::Config.new).addon_classes.sort_by(&:name)
+    end
+
     def load_phases
       Dir.glob(__dir__ + '/phases/*.rb').each { |f| require(f) }
```
Comment (SpComb) [inline lib/pharos/version_command.rb]: Can be changed to `Pharos::PhaseManager.load_phases(__dir__ + '/addons')`

File: lib/pharos/version_command.rb [hunk 2]
```diff
@@ -5,18 +5,31 @@ class VersionCommand < Pharos::Command
...
         puts "  - #{c.name}=#{c.version} (#{c.license})"
       end
     end
 
+    def phases
+      Pharos::Phases.components.sort_by(&:name)
+    end
+
+    def addons
+      Pharos::AddonManager.new(Pharos::Config.new).addon_classes.sort_by(&:name)
```
Comment (SpComb) [inline lib/pharos/version_command.rb]: The fake `new` could be avoided, because the `addon_classes` isn't actually an instance method:

```
Pharos::AddonManager.load_addons(__dir__ + '/addons')
Pharos::Addon.descendants
```

Comment (jakolehm) [reply lib/pharos/version_command.rb]: Fixed.
