### PR TITLE
Fix nested addon configuration validation errors

### LINKED ISSUE #998: Validation error handling cannot handle nested errors
**What happened**:

Pharos throws mystic `NoMethodError` if for example addon is missing nested keys.

```
ERROR: NoMethodError : undefined method `join' for {:region=>["is missing"], :bucket=>["is missing"]}:Hash
```

**What you expected to happen**:

Validation error handling should not explode.

**cluster.yml:**

```yaml
addons:
  kontena-backup:
   enabled: true
   cloud_credentials: /path/minio_credentials
   aws:
     s3_force_path_style: true
     s3_url: foo.com/minio/test
```

### PR DESCRIPTION
**Pull request by kke**
Fixes #998 

From:
```
ERROR: NoMethodError : undefined method `join' for #<Hash:0x00007f90e1206560>
```

To:

image

### CODE REVIEW

File: lib/pharos/addon_manager.rb [hunk 1]
```diff
@@ -74,8 +75,7 @@ def validate
       with_enabled_addons do |addon_class, config|
         outcome = addon_class.validate(config)
         unless outcome.success?
-          error_msg = "#{addon_class.addon_name} => " + outcome.errors.map { |key, value| "#{key} #{value.join(',')}" }.flatten.join(', ')
-          raise InvalidConfig, error_msg
+          raise InvalidConfig, YAML.dump(addon_class.addon_name => outcome.errors.deep_stringify_keys).gsub(/^---$/, '')
```
Comment (jakolehm) [inline lib/pharos/addon_manager.rb]: This is a really clever fix 👍 Would be great to have specs also.
