### PR TITLE
Fix kubelet --cluster-dns for customized network service_cidr

### LINKED ISSUE #137: kubelet --cluster-dns assumes default network.service_cidr
The `network.service_cidr` defaults to `10.96.0.0/12` but is configurable... however, it is also hardcoded in some places that would need templating:

* https://github.com/kontena/kupo/blob/57f3f8a5af5ab9e6067e5b4f88e7eae82b9655ee/lib/kupo/scripts/configure-kube.sh#L17

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #137 

```yaml
network:
  service_cidr: 10.250.0.0/16
  pod_network_cidr: 10.32.0.0/12
```

```
$ sudo systemctl cat kubelet
# /lib/systemd/system/kubelet.service
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
ExecStart=/usr/bin/kubelet
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $K
# /etc/systemd/system/kubelet.service.d/5-pharos.conf
[Service]
Environment='KUBELET_EXTRA_ARGS=--node-ip=167.99.36.141 --hostname-override=terom-kupo-master'
Environment='KUBELET_DNS_ARGS=--cluster-dns=10.250.0.10 --cluster-domain=cluster.local'
ExecStartPre=-/sbin/swapoff -a
```

(not entirely sure why the `Environment="KUBELET_DNS_ARGS=..."` in the `5-pharos.conf` overrides the environment in the `10-kubeadm.conf`, but it does)

```
$ ps aux | grep kubelet | grep -oE -- '--cluster-dns=\S+'
--cluster-dns=10.250.0.10
```

```
$ kubectl run -it --attach --rm --restart=Never curl -l role=test --image=byrnedo/alpine-curl --command -- cat /etc/resolv.conf
nameserver 10.250.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
$ kubectl run -it --attach --rm --restart=Never curl -l role=test --image=byrnedo/alpine-curl -- -vk https://kubernetes
* Rebuilt URL to: https://kubernetes/
*   Trying 10.250.0.1...
* TCP_NODELAY set
* Connected to kubernetes (10.250.0.1) port 443 (#0)
```

### CODE REVIEW

File: lib/pharos/phases/configure_kubelet.rb [hunk 1]
```diff
@@ -1,6 +1,7 @@
 # frozen_string_literal: true
 
 require_relative 'base'
+require_relative 'component'
```
Comment (SpComb) [inline lib/pharos/phases/configure_kubelet.rb]: Dunno how the autoloader is supposed to work with specs

```

An error occurred while loading ./spec/pharos/phases/configure_kubelet_spec.rb.
Failure/Error:
  Pharos::Phases::Component.new(
    name: 'kubernetes', version: Pharos::KUBE_VERSION, license: 'Apache License 2.0'
  )

NameError:
  uninitialized constant Pharos::Phases::Component
  Did you mean?  Complex
# ./lib/pharos/phases/configure_kubelet.rb:9:in `<class:ConfigureKubelet>'
# ./lib/pharos/phases/configure_kubelet.rb:7:in `<module:Phases>'
# ./lib/pharos/phases/configure_kubelet.rb:6:in `<module:Pharos>'
# ./lib/pharos/phases/configure_kubelet.rb:5:in `<top (required)>'
# ./spec/pharos/phases/configure_kubelet_spec.rb:2:in `require'
# ./spec/pharos/phases/configure_kubelet_spec.rb:2:in `<top (required)>'


Finished in 0.00022 seconds (files took 0.79165 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
