### PR TITLE
Fix hostname and address uniqueness validation for hosts sharing an IP

### LINKED ISSUE #1439: Validate hostname uniqueness does not take into account ssh port
Same hostname can have multiple nodes in different ssh ports.. now validation blocks these usecases.

### PR DESCRIPTION
**Pull request by kke**
Fixes #1439

Hostname uniqueness check would ignore hosts with the same IP address but a different SSH port.

A host with a non-uniqu address but a different SSH port would have been considered a duplicate, eventhough it's likely a port forward.

### CODE REVIEW

File: lib/pharos/phases/validate_host.rb [hunk 1]
```diff
@@ -44,10 +44,10 @@ def check_role
       end
 
       def validate_unique_hostnames
-        duplicates = @config.hosts.reject { |h| h.address == @host.address }.select { |h| h.hostname == @host.hostname }
+        duplicates = @config.hosts.reject { |h| h.address == @host.address }.select { |h| h.hostname == @host.hostname && h.ssh_port == @host.ssh_port }
```
Comment (jakolehm) [inline lib/pharos/phases/validate_host.rb]: Hmm... why are we calling this unique hostnames and then we validate unique addresses? 🤔

Comment (kke) [reply lib/pharos/phases/validate_host.rb]: `GatherFacts` does `host.hostname = transport.exec("hostname -f")`.

If it's a port forward to some other host, it should get a different hostname anyway. 

Maybe the unique hostname thing actually needs to just check for duplicate hostnames, no matter what the address / port is, so something like `(@config.hosts - [@host]).find { |h| h.hostname == @host.hostname }` ?

Comment (kke) [reply lib/pharos/phases/validate_host.rb]: Hmm, in fact, I think instead of reporting hostnames as duplicate, it should have been allowing duplicate hostnames for hosts with the same address?

`@config.hosts.reject { |h| h.address == @host.address }` would have been empty if there were two hosts with the same address but different ssh ports.

Comment (jakolehm) [reply lib/pharos/phases/validate_host.rb]: We are mixing two different things here:
1. uniqueness of address:port which is used for ssh
2. uniqueness of hostname which is used to identify nodes in kubernetes

Comment (kke) [reply lib/pharos/phases/validate_host.rb]: config_schema will complain if addresses are equal and does not check ssh_port.

Needs to be fixed also.

**Comment by kke** [comment]
Added host:ssh_port uniqueness validation and removed the unique address validation.

Had to resort to trickery in `ConfigSchema#load` because couldn't think of a way to do it with a dry predicate.

File: lib/pharos/config_schema.rb [hunk 2]
```diff
@@ -34,6 +34,16 @@ def self.load(data)
       result = schema.call(DEFAULT_DATA.merge(data))
       raise Pharos::ConfigError, result.messages unless result.success?
 
+      messages = { hosts: {} }
```
Comment (jakolehm) [inline lib/pharos/config_schema.rb]: IMO this can be implemented as predicate

```ruby
    def self.build
      # rubocop:disable Lint/NestedMethodDefinition
      Dry::Validation.Params do
        configure do

          # @param hosts [Array<Hash>]
          def unique_addresses?(hosts)
            return false if hosts.group_by { |host| "#{host[:address]}:#{host[:ssh_port]}" }.size < hosts.size

            true
          end
```

```ruby
required(:hosts).filled(:unique_addresses?, min_size?: 1) do
```

**Comment by kke** [comment]
Now uses a predicate.

- It does not tell which host is non-unique
- The message is displayed also when the `hosts:` is missing.
- When it fails, it always makes `size cannot be less than 1` appear also, I suppose it clears the "non valid" `hosts:` and then decides it's too small.

File: spec/pharos/phases/validate_host_spec.rb [hunk 3]
```diff
@@ -150,12 +150,27 @@
...
+        before do
+          config.hosts[0].attributes[:address] = '192.0.2.2'
+          config.hosts[1].attributes[:address] = '192.0.2.2'
+          config.hosts[0].attributes[:ssh_port] = 8022
+          config.hosts[1].attributes[:ssh_port] = 22
+        end
 
-        expect{ subject.validate_unique_hostnames }.to raise_error(Pharos::InvalidHostError, "Duplicate hostname foo for hosts 192.0.2.2,192.0.2.3")
+        it 'raises if duplicates' do
+          expect{ subject.validate_unique_hostnames }.to raise_error(Pharos::InvalidHostError, "Duplicate hostname foo for hosts 192.0.2.2:22,192.0.2.3:22")
```
Comment (kke) [inline spec/pharos/phases/validate_host_spec.rb]: Hmm, how can this pass? This sort of message is not there anymore

Comment (kke) [reply spec/pharos/phases/validate_host_spec.rb]: Ah, it's in the phase.
