### PR TITLE
Fix host role checks to skip unconfigured hosts

### LINKED ISSUE #332: Cannot add a fresh master
Regression from #331.

```
Pharos::InvalidHostError : Cannot change role of an existing node
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #332

Minimal fix to skip the role checks if the kubelet was not yet configured. Tested to worker for `role` changes after a succesfull `pharos-cluster up`.

### CODE REVIEW

File: lib/pharos/phases/validate_host.rb [hunk 1]
```diff
@@ -89,15 +92,18 @@ def cpu_arch
...
         data = {}
-        result = @ssh.exec("sudo curl -sSf --connect-timeout 1 --cacert /etc/kubernetes/pki/ca.crt https://localhost:6443/healthz")
-        data['api_healthy'] = (result.success? && result.stdout == 'ok')
-        data['ca_exists'] = @ssh.file('/etc/kubernetes/pki/ca.key').exist?
         data['kubelet_configured'] = @ssh.file('/etc/kubernetes/kubelet.conf').exist?
+        data['ca_exists'] = @ssh.file('/etc/kubernetes/pki/ca.key').exist?
+        data['etcd_ca_exists'] = @ssh.file('/etc/pharos/pki/ca-key.pem').exist?
+
+        if data['ca_exists']
+          result = @ssh.exec("sudo curl -sSf --connect-timeout 1 --cacert /etc/kubernetes/pki/ca.crt https://localhost:6443/healthz")
```
Comment (SpComb) [inline lib/pharos/phases/validate_host.rb]: Unrelated change, but we don't need to bother with the `curl` if the CA cert that it's using doesn't exist?

File: lib/pharos/phases/validate_host.rb [hunk 2]
```diff
@@ -43,10 +43,13 @@ def gather_host_facts
       end
 
       def check_role
-        return if @host.master? && @host.checks['ca_exists'] == true
-        return if @host.worker? && @host.checks['kubelet_configured'] && @host.checks['ca_exists'] != true
+        return if !@host.checks['kubelet_configured']
```
Comment (SpComb) [inline lib/pharos/phases/validate_host.rb]: This will not work correctly if the cluster setup failed after the `ConfigureKubelet`/`ConfigureEtcd` phases but before the `ConfigureMaster`/`JoinNode` phases, and the role was then changed... Might be better to check for the `/etc/kubernetes/manifests/*` files instead ( `pharos-proxy`, `pharos-etcd` and `kube-apiserver`), since AFAIK those are what actually cause the actual role incompatibilities per #305.

File: lib/pharos/phases/validate_host.rb [hunk 3]
```diff
@@ -43,10 +43,13 @@ def gather_host_facts
...
 
-        raise Pharos::InvalidHostError, "Cannot change role of an existing node"
+        if @host.master? && !@host.checks['ca_exists']
```
Comment (SpComb) [inline lib/pharos/phases/validate_host.rb]: I'm guessing the rubocop suggestino to use a "guard clause instead" isn't just referring to `return`, because I don't see how to transform this code with the two different `raise` exceptions to use `return`... but `raise ... if ...` does work, and I guess that also coutns as a "guard clause"

```
lib/pharos/phases/validate_host.rb:48:9: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
        if @host.master? && !@host.checks['ca_exists']
        ^^

```

File: lib/pharos/phases/validate_host.rb (hunk 1 above)
Comment (jakolehm) [reply lib/pharos/phases/validate_host.rb]: True.

File: spec/pharos/phases/validate_host_spec.rb [hunk 4]
```diff
@@ -53,55 +53,99 @@
...
+          'ca_exists' => false,
+          'api_healthy' => false,
+          'kubelet_configured' => false
+        } }
 
-      subject = described_class.new(worker, config: config, ssh: ssh)
-      expect{ subject.check_role }.not_to raise_error
-    end
+        it 'does not raise' do
+          expect{ subject.check_role }.to_not raise_error(Pharos::InvalidHostError)
```
Comment (SpComb) [inline spec/pharos/phases/validate_host_spec.rb]: And `expect{...}.to_not raise_error(...)` is also a bad idea...
